name: Server PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: [self-hosted, local, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Run Lint
        run: ./gradlew lint
        shell: bash

      - name: Run Unit Tests
        run: ./gradlew test
        shell: bash

      - name: Build JAR
        run: ./gradlew build
        shell: bash
