name: Backend PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-check:
    runs-on: [self-hosted, local, backend]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Lint
        shell: powershell
        run: .\gradlew ktlintCheck

      - name: Tests
        shell: powershell
        run: .\gradlew test

      - name: Build
        shell: powershell
        run: .\gradlew build
